// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Logo field in *Navigation*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Contact field in *Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.contact
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  contact: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Footer field in *Navigation*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.footer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footer: prismic.RichTextField;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | ImagesSectionSlice
  | TitleSectionSlice
  | SliderItemSlice
  | ImageSectionSlice
  | HeroSectionSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = NavigationDocument | PageDocument;

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * Video field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.video
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Title field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Primary content in *ImageSection → Default → Primary*
 */
export interface ImageSectionSliceDefaultPrimary {
  /**
   * Image field in *ImageSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Caption field in *ImageSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_section.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  caption: prismic.RichTextField;

  /**
   * Full Width field in *ImageSection → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_section.default.primary.full_width
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  full_width: prismic.BooleanField;
}

/**
 * Default variation for ImageSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageSection*
 */
type ImageSectionSliceVariation = ImageSectionSliceDefault;

/**
 * ImageSection Shared Slice
 *
 * - **API ID**: `image_section`
 * - **Description**: ImageSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSectionSlice = prismic.SharedSlice<
  "image_section",
  ImageSectionSliceVariation
>;

/**
 * Primary content in *ImagesSection → Default → Primary*
 */
export interface ImagesSectionSliceDefaultPrimary {
  /**
   * Image 1 field in *ImagesSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: images_section.default.primary.image_1
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Image 2 field in *ImagesSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: images_section.default.primary.image_2
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_2: prismic.ImageField<never>;

  /**
   * Caption field in *ImagesSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: images_section.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  caption: prismic.RichTextField;
}

/**
 * Default variation for ImagesSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImagesSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImagesSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImagesSection*
 */
type ImagesSectionSliceVariation = ImagesSectionSliceDefault;

/**
 * ImagesSection Shared Slice
 *
 * - **API ID**: `images_section`
 * - **Description**: ImagesSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImagesSectionSlice = prismic.SharedSlice<
  "images_section",
  ImagesSectionSliceVariation
>;

/**
 * Primary content in *TextSection → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *TextSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Align Right field in *TextSection → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: rich_text.default.primary.align_right
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  align_right: prismic.BooleanField;
}

/**
 * Default variation for TextSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextSection*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * TextSection Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Item in *SliderItem → Default → Primary → Images*
 */
export interface SliderItemSliceDefaultPrimaryImagesItem {
  /**
   * Image field in *SliderItem → Default → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slider_item.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Caption field in *SliderItem → Default → Primary → Images*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slider_item.default.primary.images[].caption
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  caption: prismic.RichTextField;
}

/**
 * Primary content in *SliderItem → Default → Primary*
 */
export interface SliderItemSliceDefaultPrimary {
  /**
   * Images field in *SliderItem → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: slider_item.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  images: prismic.GroupField<Simplify<SliderItemSliceDefaultPrimaryImagesItem>>;
}

/**
 * Default variation for SliderItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SliderItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SliderItemSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SliderItem*
 */
type SliderItemSliceVariation = SliderItemSliceDefault;

/**
 * SliderItem Shared Slice
 *
 * - **API ID**: `slider_item`
 * - **Description**: SliderItem
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SliderItemSlice = prismic.SharedSlice<
  "slider_item",
  SliderItemSliceVariation
>;

/**
 * Primary content in *TitleSection → Default → Primary*
 */
export interface TitleSectionSliceDefaultPrimary {
  /**
   * Title field in *TitleSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for TitleSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TitleSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TitleSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TitleSection*
 */
type TitleSectionSliceVariation = TitleSectionSliceDefault;

/**
 * TitleSection Shared Slice
 *
 * - **API ID**: `title_section`
 * - **Description**: TitleSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TitleSectionSlice = prismic.SharedSlice<
  "title_section",
  TitleSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      NavigationDocument,
      NavigationDocumentData,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      ImageSectionSlice,
      ImageSectionSliceDefaultPrimary,
      ImageSectionSliceVariation,
      ImageSectionSliceDefault,
      ImagesSectionSlice,
      ImagesSectionSliceDefaultPrimary,
      ImagesSectionSliceVariation,
      ImagesSectionSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      SliderItemSlice,
      SliderItemSliceDefaultPrimaryImagesItem,
      SliderItemSliceDefaultPrimary,
      SliderItemSliceVariation,
      SliderItemSliceDefault,
      TitleSectionSlice,
      TitleSectionSliceDefaultPrimary,
      TitleSectionSliceVariation,
      TitleSectionSliceDefault,
    };
  }
}
