// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero_section: dynamic(() => import("./HeroSection")),
  image_section: dynamic(() => import("./ImageSection")),
  images_section: dynamic(() => import("./ImagesSection")),
  rich_text: dynamic(() => import("./TextSection")),
  slider_item: dynamic(() => import("./SliderItem")),
  title_section: dynamic(() => import("./TitleSection")),
};
